# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventario_pb2 as inventario__pb2

GRPC_GENERATED_VERSION = '1.65.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in inventario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class InventarioStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CrearProducto = channel.unary_unary(
                '/Inventario/CrearProducto',
                request_serializer=inventario__pb2.Producto.SerializeToString,
                response_deserializer=inventario__pb2.Respuesta.FromString,
                _registered_method=True)
        self.ObtenerProducto = channel.unary_unary(
                '/Inventario/ObtenerProducto',
                request_serializer=inventario__pb2.IdProducto.SerializeToString,
                response_deserializer=inventario__pb2.Producto.FromString,
                _registered_method=True)
        self.ActualizarProducto = channel.unary_unary(
                '/Inventario/ActualizarProducto',
                request_serializer=inventario__pb2.Producto.SerializeToString,
                response_deserializer=inventario__pb2.Respuesta.FromString,
                _registered_method=True)
        self.EliminarProducto = channel.unary_unary(
                '/Inventario/EliminarProducto',
                request_serializer=inventario__pb2.IdProducto.SerializeToString,
                response_deserializer=inventario__pb2.Respuesta.FromString,
                _registered_method=True)
        self.ListarProductos = channel.unary_unary(
                '/Inventario/ListarProductos',
                request_serializer=inventario__pb2.Vacio.SerializeToString,
                response_deserializer=inventario__pb2.ListaProductos.FromString,
                _registered_method=True)


class InventarioServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CrearProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ObtenerProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarProductos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventarioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CrearProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.CrearProducto,
                    request_deserializer=inventario__pb2.Producto.FromString,
                    response_serializer=inventario__pb2.Respuesta.SerializeToString,
            ),
            'ObtenerProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.ObtenerProducto,
                    request_deserializer=inventario__pb2.IdProducto.FromString,
                    response_serializer=inventario__pb2.Producto.SerializeToString,
            ),
            'ActualizarProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarProducto,
                    request_deserializer=inventario__pb2.Producto.FromString,
                    response_serializer=inventario__pb2.Respuesta.SerializeToString,
            ),
            'EliminarProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarProducto,
                    request_deserializer=inventario__pb2.IdProducto.FromString,
                    response_serializer=inventario__pb2.Respuesta.SerializeToString,
            ),
            'ListarProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarProductos,
                    request_deserializer=inventario__pb2.Vacio.FromString,
                    response_serializer=inventario__pb2.ListaProductos.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Inventario', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Inventario', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Inventario(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CrearProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Inventario/CrearProducto',
            inventario__pb2.Producto.SerializeToString,
            inventario__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ObtenerProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Inventario/ObtenerProducto',
            inventario__pb2.IdProducto.SerializeToString,
            inventario__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Inventario/ActualizarProducto',
            inventario__pb2.Producto.SerializeToString,
            inventario__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Inventario/EliminarProducto',
            inventario__pb2.IdProducto.SerializeToString,
            inventario__pb2.Respuesta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Inventario/ListarProductos',
            inventario__pb2.Vacio.SerializeToString,
            inventario__pb2.ListaProductos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
