# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventario.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10inventario.proto\"]\n\x08Producto\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scripcion\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61ntidad\x18\x04 \x01(\x05\x12\x0e\n\x06precio\x18\x05 \x01(\x01\"\x18\n\nIdProducto\x12\n\n\x02id\x18\x01 \x01(\t\"\x1c\n\tRespuesta\x12\x0f\n\x07mensaje\x18\x01 \x01(\t\"\x07\n\x05Vacio\".\n\x0eListaProductos\x12\x1c\n\tproductos\x18\x01 \x03(\x0b\x32\t.Producto2\xe5\x01\n\nInventario\x12&\n\rCrearProducto\x12\t.Producto\x1a\n.Respuesta\x12)\n\x0fObtenerProducto\x12\x0b.IdProducto\x1a\t.Producto\x12+\n\x12\x41\x63tualizarProducto\x12\t.Producto\x1a\n.Respuesta\x12+\n\x10\x45liminarProducto\x12\x0b.IdProducto\x1a\n.Respuesta\x12*\n\x0fListarProductos\x12\x06.Vacio\x1a\x0f.ListaProductosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCTO']._serialized_start=20
  _globals['_PRODUCTO']._serialized_end=113
  _globals['_IDPRODUCTO']._serialized_start=115
  _globals['_IDPRODUCTO']._serialized_end=139
  _globals['_RESPUESTA']._serialized_start=141
  _globals['_RESPUESTA']._serialized_end=169
  _globals['_VACIO']._serialized_start=171
  _globals['_VACIO']._serialized_end=178
  _globals['_LISTAPRODUCTOS']._serialized_start=180
  _globals['_LISTAPRODUCTOS']._serialized_end=226
  _globals['_INVENTARIO']._serialized_start=229
  _globals['_INVENTARIO']._serialized_end=458
# @@protoc_insertion_point(module_scope)
